name: music_sns
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  freezed:
  cupertino_icons: ^1.0.2
  dartz:
  uuid:
  get_it:
  injectable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed_annotation:
  injectable_generator:
  build_runner:


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom font to your application, add a font section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "font" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # font:
  #   - family: Schyler
  #     font:
  #       - asset: font/Schyler-Regular.ttf
  #       - asset: font/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     font:
  #       - asset: font/TrajanPro.ttf
  #       - asset: font/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding font from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

fonts:
  - family: SpoqaHanSansNeo
    fonts:
      - asset: assets/font/SpoqaHanSansNeo_OTF_subset/SpoqaHanSansNeo-Thin.otf
        weight: 100
      - asset: assets/font/SpoqaHanSansNeo_OTF_subset/SpoqaHanSansNeo-Light.otf
        weight: 300
      - asset: assets/font/SpoqaHanSansNeo_OTF_subset/SpoqaHanSansNeo-Regular.otf
        weight: 400
      - asset: assets/font/SpoqaHanSansNeo_OTF_subset/SpoqaHanSansNeo-Medium.otf
        weight: 500
      - asset: assets/font/SpoqaHanSansNeo_OTF_subset/SpoqaHanSansNeo-Bold.otf
        weight: 700
